### ISSUE TITLE
Contract template(s)?

### ISSUE THREAD

**Issue by varmais** [sam-hosseini/freelancing-in-finland#44]
Should we include some basic contracts templates for freelancers to use when needed? Usually with brokers and bigger companies they have their own templates but when one's client is purchasing IT-contractor the first time they probably don't have contract templates in hand. Would give a professional impression if one had one ready and it is one of the frequently asked questions I stumble upon wether someone has contract template and/or what it should cover.

- [x] I have read and taken into account [CONTRIBUTING.md](https://github.com/sam-hosseini/freelancing-in-finland/blob/master/CONTRIBUTING.md) ✨🚀💯

**Comment by sam-hosseini** [comment]
Hi Teemu!

> Should we include some basic contracts templates for freelancers to use when needed?

Absolutely. I hadn't thought about this usecase because as you mentioned, brokers and bigger companies often have their own contracts and therefore the freelancer doesn't have to have his/her own. But it's definitely a scenario that could happen for the target audience of this guide, e.g. when building a small website for a small local business, and in that case, the small local business would reasonably expect the IT freelancer to have a contract template at least. Wonderful suggestion 👍🏼

I called Suomen Yrittäjät union to ask if they have a template they can share openly and any possible advice. Will update here once their lawyer gets back to me.

In the meantime, do you @varmais have a template on hand you can share? 😊

For implementation, I'm thinking of a `contract-templates` folder within which we put contract template(s) as long as they're relavent to the target audience of the guide. And mention it in the [Wait until you find a project you like](https://github.com/sam-hosseini/freelancing-in-finland#wait-until-you-find-a-project-you-like) steps with something along the lines of "If your client doesn't have its own contract and asks you for one, you can use this/that link, etc etc", but this is still open.

**Comment by varmais** [comment]
As an attachment is at least one simple version that covers the basics and is fair on both sides that we recommend to people. Feel free to use it here as well. =)

IT2000 Terms & Conditions are also great starting point but I think they are a bit on the heavy side for smaller clients/projects.

[Resource Hiring Agreement.docx](https://github.com/sam-hosseini/freelancing-in-finland/files/5702314/Resource.Hiring.Agreement.docx)

**Comment by sam-hosseini** [comment]
@allcontributors add @varmais to contributors for doc

**Comment by sam-hosseini** [comment]
I also read the simple version and I think it's surely a good document to start with and it does look to me that it tries to safeguard both side's interests. Especially the section about putting a 20% cap on the total liability was solid 👌🏼 and one can always add and update sections to the template based on their circumstances.

Thank you for your contribution @varmais ! 😊
