### ISSUE TITLE
Double taxation

### ISSUE THREAD

**Issue by igagis** [sam-hosseini/freelancing-in-finland#53]
Hi,

thanks for the great guide!

I have a question about double taxation. This relates to the way of taking money out of the company. My understanding is that company has to pay _corporate tax_ of 20% and, at the same time, when paying out dividends to shareholders they have to pay capital income tax of about ~30%.

So, do I understand right that, if I'm the only shareholder of the company and I don't get salary all year, then at the end of the year I want to extract all the money earned by company via dividends, then I will effectively pay as taxes 20% of company money and then from the rest I pay ~30%?

This seems a lot, isn't it better to pay all the money as salary and pay individual income tax?
Using [this calculator](https://osinkoavaipalkkaa.fi/) it looks like if you want to extract all the money from company each year then the best option is to pay everything as salary, or do I miss something? What is the benefit of freelancing in this case in comparison to employment with same hourly rate?

**Comment by sam-hosseini** [comment]
Hi Ivan! 👋🏼

You're asking the million-dollar question 😄

> What is it? Taking money from the company in the most tax optimal way is a million-dollar question. Only a team of competent accountants and competent lawyers specializing in coporate tax law could answer that question.

I'll briefly cover the main points:

> I have a question about double taxation. This relates to the way of taking money out of the company. My understanding is that company has to pay corporate tax of 20% and, at the same time, when paying out dividends to shareholders they have to pay capital income tax of about ~30%.

The way to think about this is that when you register a company, **you give birth to another human**. This human is not a natural person like me or you, but a **legal entity**. Now, just like me and you when we pay taxes on our income (individuals's income tax, individual's capital gain tax, individual's gift tax, etc), that human you gave birth to needs to pay its taxes as **corporate income tax**. If you think about it this way, there's no double-taxation, every human just paying taxes on their income 🤷🏻‍♂️

But I get your point. Effectively, you work for a client, client pays to your company. Company first pays corporate tax, and then while distributing dividends, as a natural person, you pay capital gain tax. There's indeed double taxation happening, and that's mainly because of [limited liability concept](https://www.khanacademy.org/economics-finance-domain/core-finance/taxes-topic/corporate-taxation/v/corporations-and-limited-liability) as far as I've understood it. So, it comes down to this: you want limited liability? you pay tax twice. you want unlimited liability (work under your own name with toiminimi)? you pay tax once.

> So, do I understand right that, if I'm the only shareholder of the company and I don't get salary all year, then at the end of the year I want to extract all the money earned by company via dividends, then I will effectively pay as taxes 20% of company money and then from the rest I pay ~30%?

The assumptions you've mentioned are overly simplified. First, the minimum salary you take is gonna be around 12k, and you don't need to be a accountant to know this. Why? Because salary is **cost** for the company. When you take 12k as salary, then at the end of the company fiscal year, you don't pay corporate tax on it because it was a **cost**. And when you take 12k as salary, as an individual in Helsinki, you pay 0% income tax (12k is the limit, 13k you pay 1%, and it increases). So, when you can take 12k and pay no income tax, you do it.

There's also the 8%-rule. If you don't take all the leftover of the company as dividend but only 8%, then on that 8% you take out, you pay only 7.5% tax. So, if you have 1 million euro in the company, and you take out 80k, on that 80k, you pay only 6k of capital gain tax. And that is why a lot of people don't take more than 8% dividend, because if you take more than that, then, in a simplified way, you go back to the *usual* 30% capital gain tax mode.

Reality is more complex and your accountant will help you to optimize things.

> What is the benefit of freelancing in this case in comparison to employment with same hourly rate?

Your question is hypothetical and I get it, but the thing is, it doesn't happen in reality. A senior developer making 12k/month as a freelancer is business as usual. A senior developer making 12k/month as an employee must be a truly truly truly exceptional case (I'm talking about Finland only). The absolute highest I've ever heard for a senior developer as employee was 7.5k/month. So, **same hourly rate** doesn't happen.

But given that it happens, the first benefit is that as a freelancer with limited company, you can choose your social security coverage and pay the minimum if you wish, as an employee you can't. Minimum social security for freelancers is ~2k per year, for an employee making 150k/year, it's more like ~12k. That's an immediate 10k you can benefit.

Second, is that you can have company expenses. If an employee wants to buy a 5k headphone, they need to convince their boss and most likely you get a no. If a freelancer wants to buy a 5k headphone, you can buy it, and you don't need to convince anyone (except vero 😁). So, instead of paying 5k from your pocket, which has been taxed already, you can pay 5k from your company, and since it's a cost, it's never been taxed. On top of that, you get the VAT of 5k back, so effectively it becomes more like 4k.

I wish you all the best in your journey if you decide to do it 👍🏼

**Comment by igagis** [comment]
Hi Sam!

Thank you for detailed answer. I still have couple of questions though.

1. > And when you take 12k as salary, as an individual in Helsinki, you pay 0% income tax (12k is the limit, 13k you pay 1%, and it increases). So, when you can take 12k and pay no income tax, you do it.

    do you mean 12k for the whole year or per month? My intention is to have 12k per month, so in this case as I understand I will have to pay normal income tax of about 35% from those 12k, right?
If you meant 12k per month, could you give some links to official information about that income tax from 12k/month for individuals is 0%?

2. I found that in US there is possibility to establish so called [S corporation](https://www.investopedia.com/terms/s/subchapters.asp) and thus avoid the double taxation. How do you think, maybe in Finland there is some similar thing?
Also, from [this Khan academy video](https://www.khanacademy.org/economics-finance-domain/core-finance/taxes-topic/corporate-taxation/v/is-limited-liability-or-double-taxation-fair) (see from 4:30) I found that in US there are other forms of limited liability companies like LLC which also do not have double taxation. Is it so that in Finland there are no such options?

**Comment by sam-hosseini** [comment]
You're welcome!

1. I surely meant no tax for 12k for the whole year. You're right, if you take 12k/month, you will pay the highest income tax bracket which is likely the 35% you mentioned 👍🏼

2. I have no knowledge or understanding about corporation types in the US and therefore can't think of equivalent corporate types in Finland.

Btw, if you would like to keep this thread in the future for yourself, could you copy/download it today? Tomorrow I'm disabling `issues` on this repository, and that'd disable accessing this thread.

**Comment by igagis** [comment]
Thanks, I don't need to keep this thread, I have the info I needed now. I just thought that since the questions arise, maybe some more details on the topic could be added to the original document you have created. So, other people in future would not ask same question again :)

**Comment by sam-hosseini** [comment]
> Thanks, I don't need to keep this thread, I have the info I needed now.

Glad you have the info already 👍🏼

> I just thought that since the questions arise, maybe some more details on the topic could be added to the original document you have created. So, other people in future would not ask same question again :)

It's by intentional design that I have not added more information to the guide about taking out money from the company. I think that anything outside the fundamentals of money (like the picture in the guide) is gonna cause so many different scenarios in people's mind and so many questions that it'd be impractical for me to handle. I think it's best people ask from their own accountants/lawyers/counsolours how to optimize their money situation with respect to their company.
